import type { FacturationTableRow } from "@/components/facturation/FacturationTable";

/**
 * Cas limites du registre de facturation (M1).
 *
 * Ce ne sont pas huit lignes moyennes : c'est ce qui casse une mise en page.
 * Nom de client très long, intitulé de dossier très long, montant à sept
 * chiffres, facture sans dossier, solde nul, facture en retard relancée deux
 * fois, brouillon sans échéance utile, paiement partiel à 3 %.
 */
const aout = (n: number) => new Date(2026, 7, n);
const septembre = (n: number) => new Date(2026, 8, n);

export const RANGEES: FacturationTableRow[] = [
  {
    id: "ap-1",
    clientEmail: "ap-1@example.ca",
    cabinetNom: "Cabinet Roy",
    joursDeRetard: 25,
    numero: "2026-0042",
    client: "Groupe immobilier Northfield et Associés inc.",
    clientId: "c1",
    dossier: "Northfield c. Ville de Laval — recours en annulation de règlement de zonage",
    dossierId: "d1",
    dateEmission: aout(2),
    dateEcheance: aout(2),
    montantTotal: 1_284_300.5,
    balanceDue: 1_284_300.5,
    statut: "en_retard",
    lastReminderDay: 30,
    lastReminderSentAt: aout(20),
  },
  {
    id: "ap-2",
    clientEmail: "ap-2@example.ca",
    cabinetNom: "Cabinet Roy",
    joursDeRetard: 0,
    numero: "2026-0041",
    client: "Tremblay-Beauchemin, Jean-Christophe",
    clientId: "c2",
    dossier: "Séparation de corps",
    dossierId: "d2",
    dateEmission: aout(9),
    dateEcheance: aout(24),
    montantTotal: 4_312.75,
    balanceDue: 4_182.75,
    statut: "partiellement_payee",
    lastReminderDay: null,
    lastReminderSentAt: null,
  },
  {
    id: "ap-3",
    clientEmail: "ap-3@example.ca",
    cabinetNom: "Cabinet Roy",
    joursDeRetard: 0,
    numero: "2026-0040",
    client: "Boulangerie Saint-Roch inc.",
    clientId: "c3",
    dossier: "—",
    dossierId: null,
    dateEmission: aout(11),
    dateEcheance: aout(26),
    montantTotal: 862.5,
    balanceDue: 0,
    statut: "payee",
    lastReminderDay: null,
    lastReminderSentAt: null,
  },
  {
    id: "ap-4",
    clientEmail: "ap-4@example.ca",
    cabinetNom: "Cabinet Roy",
    joursDeRetard: 0,
    numero: "2026-0039",
    client: "Ouellet, Marie-Ève",
    clientId: "c4",
    dossier: "Contestation de saisie avant jugement",
    dossierId: "d4",
    dateEmission: aout(14),
    dateEcheance: aout(29),
    montantTotal: 18_940,
    balanceDue: 18_940,
    statut: "envoyee",
    lastReminderDay: 7,
    lastReminderSentAt: aout(21),
  },
  {
    id: "ap-5",
    clientEmail: "ap-5@example.ca",
    cabinetNom: "Cabinet Roy",
    joursDeRetard: 0,
    numero: "2026-0038",
    client: "Coopérative de solidarité des Berges",
    clientId: "c5",
    dossier: "Révision de la convention d'actionnaires",
    dossierId: "d5",
    dateEmission: aout(15),
    dateEcheance: aout(30),
    montantTotal: 7_250,
    balanceDue: 7_032.5,
    statut: "partiellement_payee",
    lastReminderDay: null,
    lastReminderSentAt: null,
  },
  {
    id: "ap-6",
    clientEmail: null,
    cabinetNom: "Cabinet Roy",
    joursDeRetard: 10,
    numero: "2026-0037",
    client: "Succession de feu Roland Bergeron",
    clientId: "c6",
    dossier: "Liquidation successorale",
    dossierId: "d6",
    dateEmission: aout(17),
    dateEcheance: aout(17),
    montantTotal: 3_105.2,
    balanceDue: 3_105.2,
    statut: "en_retard",
    lastReminderDay: 15,
    lastReminderSentAt: aout(24),
  },
  {
    id: "ap-7",
    clientEmail: "ap-7@example.ca",
    cabinetNom: "Cabinet Roy",
    joursDeRetard: 0,
    numero: "2026-0036",
    client: "Constructions Béliveau & Fils ltée",
    clientId: "c7",
    dossier: "Réclamation pour vices de construction",
    dossierId: "d7",
    dateEmission: aout(18),
    dateEcheance: septembre(2),
    montantTotal: 46_780.9,
    balanceDue: 46_780.9,
    statut: "brouillon",
    lastReminderDay: null,
    lastReminderSentAt: null,
  },
  {
    id: "ap-8",
    clientEmail: "ap-8@example.ca",
    cabinetNom: "Cabinet Roy",
    joursDeRetard: 0,
    numero: "2026-0035",
    client: "Ntumba Kalala, Joséphine",
    clientId: "c8",
    dossier: "Parrainage — conjoint de fait",
    dossierId: "d8",
    dateEmission: aout(20),
    dateEcheance: septembre(4),
    montantTotal: 2_400,
    balanceDue: 2_328,
    statut: "envoyee",
    lastReminderDay: null,
    lastReminderSentAt: null,
  },
];
