import { NextResponse } from "next/server";
import React from "react";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/db";
import { renderToBuffer } from "@react-pdf/renderer";
import type { DocumentProps } from "@react-pdf/renderer";
import type { UserRole } from "@prisma/client";
import { canViewFullAuditLog } from "@/lib/auth/permissions";
import { getCabinetReadiness, type ReadinessState } from "@/lib/admin/readiness";
import { generateReportData } from "@/lib/services/fideicommis/lso-report-service";
import { getCabinetProvince } from "@/lib/cabinet/get-province";
import { getTrustRegulatorCopy } from "@/lib/trust/regulator";
import {
  InspectionDossierPDF,
  type InspectionDomainRow,
  type InspectionReconRow,
  type InspectionAuditRow,
} from "@/components/conformite/InspectionDossierPDF";

const DOMAIN_TITLES: Record<string, { fr: string; en: string }> = {
  identity: { fr: "Identité du cabinet", en: "Firm identity" },
  province: { fr: "Province / juridiction", en: "Province / jurisdiction" },
  taxes: { fr: "Taxes", en: "Taxes" },
  billing: { fr: "Facturation", en: "Billing" },
  trust: { fr: "Fidéicommis", en: "Trust accounting" },
  team: { fr: "Équipe", en: "Team" },
  user_access: { fr: "Accès utilisateurs", en: "User access" },
  roles: { fr: "Rôles et permissions", en: "Roles & permissions" },
  subscription: { fr: "Abonnement", en: "Subscription" },
  retention: { fr: "Rétention documentaire", en: "Document retention" },
  audit_log: { fr: "Journal d'audit", en: "Audit log" },
  security: { fr: "Sécurité", en: "Security" },
  onboarding: { fr: "Configuration initiale", en: "Initial setup" },
  console: { fr: "Console SAFE", en: "SAFE console" },
};

const STATE_LABELS: Record<ReadinessState, { fr: string; en: string }> = {
  complete: { fr: "Conforme", en: "Compliant" },
  warning: { fr: "À surveiller", en: "Watch" },
  to_complete: { fr: "À compléter", en: "To complete" },
  blocking: { fr: "Bloquant", en: "Blocking" },
  not_applicable: { fr: "Non applicable", en: "Not applicable" },
};

const COPY = {
  fr: {
    docTitle: "Dossier d'inspection",
    provinceLabel: "Juridiction",
    barreauLabel: "Numéro de Barreau / LSO",
    sectionReadiness: "État de conformité",
    scoreLabel: "prêt pour l'inspection",
    colDomain: "Domaine",
    colState: "État",
    sectionRecon: "Rapprochements de fidéicommis (exercice courant)",
    colPeriode: "Période",
    colStatus: "Statut",
    colCertified: "Certifié le",
    colEcart: "Écart",
    certified: "Certifié",
    notCertified: "Non certifié",
    reconEmpty: "Aucun rapprochement enregistré pour l'exercice.",
    allCertified: "Les 12 rapprochements mensuels de l'exercice sont certifiés.",
    someMissing: (n: number) => `${n} mois sans rapprochement certifié.`,
    sectionAudit: "Piste d'audit (extrait récent)",
    colDate: "Date",
    colUser: "Utilisateur",
    colAction: "Action",
    auditEmpty: "Aucune entrée de journal d'audit.",
    generatedAt: (d: string) => `Généré le ${d}`,
    footer: (d: string) =>
      `Dossier d'inspection généré par SAFE le ${d}. Document interne à l'usage du cabinet, non contractuel.`,
    none: "—",
  },
  en: {
    docTitle: "Inspection dossier",
    provinceLabel: "Jurisdiction",
    barreauLabel: "Bar / LSO number",
    sectionReadiness: "Compliance status",
    scoreLabel: "inspection-ready",
    colDomain: "Domain",
    colState: "State",
    sectionRecon: "Trust reconciliations (current year)",
    colPeriode: "Period",
    colStatus: "Status",
    colCertified: "Certified on",
    colEcart: "Variance",
    certified: "Certified",
    notCertified: "Not certified",
    reconEmpty: "No reconciliation recorded for the year.",
    allCertified: "All 12 monthly reconciliations for the year are certified.",
    someMissing: (n: number) => `${n} month(s) without a certified reconciliation.`,
    sectionAudit: "Audit trail (recent excerpt)",
    colDate: "Date",
    colUser: "User",
    colAction: "Action",
    auditEmpty: "No audit log entries.",
    generatedAt: (d: string) => `Generated on ${d}`,
    footer: (d: string) =>
      `Inspection dossier generated by SAFE on ${d}. Internal firm document, non-contractual.`,
    none: "—",
  },
} as const;

const AUDIT_LIMIT = 60;

export async function GET() {
  const session = await getServerSession(authOptions);
  if (!session?.user) {
    return new NextResponse("Non autorisé", { status: 401 });
  }
  const cabinetId = (session.user as { cabinetId?: string }).cabinetId;
  const userId = (session.user as { id?: string }).id;
  const role = (session.user as { role?: string }).role as UserRole;
  if (!cabinetId || !userId) {
    return new NextResponse("Cabinet non trouvé", { status: 403 });
  }

  const province = await getCabinetProvince(cabinetId);
  const copy = getTrustRegulatorCopy(province);
  const lang: "fr" | "en" = copy.isQuebec ? "fr" : "en";
  const C = COPY[lang];

  const now = new Date();
  const year = now.getFullYear();
  const periode = `${year}-01`;

  const auditWhere: { cabinetId: string; userId?: string } = { cabinetId };
  if (!canViewFullAuditLog(role)) auditWhere.userId = userId;

  const [report, cabinet, reportData, auditLogs] = await Promise.all([
    getCabinetReadiness(cabinetId),
    prisma.cabinet.findUnique({
      where: { id: cabinetId },
      select: { nom: true, adresse: true, telephone: true, email: true, logoUrl: true, barreauNumero: true },
    }),
    generateReportData({ cabinetId, periode, type: "annual", generatedById: userId }).catch(() => null),
    prisma.auditLog.findMany({
      where: auditWhere,
      take: AUDIT_LIMIT,
      orderBy: { createdAt: "desc" },
      include: { user: { select: { nom: true, email: true } } },
    }),
  ]);

  const dateFmt = new Intl.DateTimeFormat(lang === "fr" ? "fr-CA" : "en-CA", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
  const money = new Intl.NumberFormat(lang === "fr" ? "fr-CA" : "en-CA", {
    style: "currency",
    currency: "CAD",
  });
  const generatedAtText = C.generatedAt(dateFmt.format(now));

  const domains: InspectionDomainRow[] = (report?.domains ?? []).map((d) => ({
    title: DOMAIN_TITLES[d.domain]?.[lang] ?? d.domain,
    stateLabel: STATE_LABELS[d.state][lang],
    evidence: d.action ?? d.evidence ?? null,
  }));

  const months = reportData?.annualReconciliations?.months ?? [];
  const recon: InspectionReconRow[] = months.map((m) => ({
    periode: m.periode,
    statusLabel: m.certified ? C.certified : C.notCertified,
    certifiedAtText: m.certifiedAt ? dateFmt.format(new Date(m.certifiedAt)) : C.none,
    ecartText: money.format(m.ecart ?? 0),
  }));
  const missingCount = reportData?.annualReconciliations?.missingOrUncertifiedMonths?.length ?? 0;
  const reconSummary = reportData?.annualReconciliations?.allCertified
    ? C.allCertified
    : C.someMissing(missingCount);

  const audit: InspectionAuditRow[] = auditLogs.map((a) => ({
    dateText: dateFmt.format(new Date(a.createdAt)),
    user: a.user?.nom ?? a.user?.email ?? C.none,
    action: a.action,
    entity: a.entityType ?? "",
  }));

  const doc = React.createElement(InspectionDossierPDF, {
    cabinet: {
      nom: cabinet?.nom ?? null,
      adresse: cabinet?.adresse ?? null,
      telephone: cabinet?.telephone ?? null,
      email: cabinet?.email ?? null,
      logoUrl: cabinet?.logoUrl ?? null,
    },
    labels: {
      docTitle: C.docTitle,
      generatedAt: generatedAtText,
      provinceLabel: C.provinceLabel,
      provinceValue: province ?? C.none,
      regulator: copy.isQuebec ? "Barreau du Québec" : "Law Society of Ontario",
      barreauLabel: C.barreauLabel,
      barreauValue: cabinet?.barreauNumero ?? C.none,
      sectionReadiness: C.sectionReadiness,
      scoreLabel: C.scoreLabel,
      scoreValue: report?.score ?? 0,
      colDomain: C.colDomain,
      colState: C.colState,
      sectionRecon: C.sectionRecon,
      reconSummary,
      colPeriode: C.colPeriode,
      colStatus: C.colStatus,
      colCertified: C.colCertified,
      colEcart: C.colEcart,
      reconEmpty: C.reconEmpty,
      sectionAudit: C.sectionAudit,
      colDate: C.colDate,
      colUser: C.colUser,
      colAction: C.colAction,
      auditEmpty: C.auditEmpty,
      footer: C.footer(dateFmt.format(now)),
    },
    domains,
    recon,
    audit,
  });

  const buffer = await renderToBuffer(doc as React.ReactElement<DocumentProps>);
  const filename = `dossier-inspection-${year}.pdf`;

  return new NextResponse(new Uint8Array(buffer), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${filename}"`,
    },
  });
}
