/**
 * Terminologie du compte en fidéicommis selon l'autorité réglementaire du cabinet.
 *
 * Source de vérité (Québec) : Règlement sur la comptabilité et les normes
 * d'exercice professionnel des avocats, RLRQ c. B-1, r. 5 (Barreau du Québec).
 * Voir knowledge-base/modules-safe/comptabilite/ (KB interne).
 *
 * Garde-fou conformité : le délai de « 25 jours » après la fin de période est
 * propre à l'Ontario (LSO By-Law 9, sec. 9.01). Il n'est PAS confirmé pour le
 * Québec dans la KB. On ne l'affiche donc JAMAIS pour un cabinet québécois :
 * côté QC on parle de « rapprochement mensuel à trois voies » sans chiffrer le
 * délai en jours.
 *
 * Helper pur (aucun accès Prisma, aucune dépendance UI). Utilisable côté serveur
 * comme côté client.
 */

export type TrustRegulatorCopy = {
  isQuebec: boolean;
  /** Autorité réglementaire (ex. "Barreau du Québec"). */
  authority: string;
  /** Référence courte (ex. "Règlement B-1, r. 5"). */
  regulationShort: string;
  /** Référence longue, pour les descriptions. */
  regulationLong: string;

  // ── Libellés de pages / sections ─────────────────────────────
  trustReconciliationTitle: string;
  trustReconciliationDesc: string;
  trustReportsTitle: string;
  trustReportsDesc: string;
  backToTrustAccounts: string;
  complianceTitle: string;
  complianceDesc: string;

  // ── Composants fidéicommis ───────────────────────────────────
  reconciliationHeading: string; // titre du formulaire de rapprochement
  certificationStatement: string; // case à cocher de certification
  reportGeneratorTitle: string;
  reportGeneratorDesc: string;
  reportStatementTitle: string; // "Trust Account Statement" / "Relevé du compte en fidéicommis"
  threeWayReconciliation: string;
  foundationInterestLabel: string; // intérêts (LFO en ON, fonds du Barreau en QC)

  // ── ReconciliationWorkflow : formulaire ──────────────────────
  reconcileNewPeriod: string; // "New Period" / "Nouvelle période"
  reconcileFormIntro: string; // intro du formulaire
  reconcileFieldPeriod: string; // "Period (YYYY-MM)"
  reconcileFieldBankStatementBalance: string; // "Bank Statement Balance ($)"
  reconcileFieldOutstandingCheques: string; // "Outstanding Cheques ($)"
  reconcileFieldDepositsInTransit: string; // "Deposits in Transit ($)"
  reconcileFieldFoundationInterestPayable: string; // "LFO Interest Payable ($)" / "Intérêts au fonds du Barreau à verser ($)"
  reconcileFieldNotes: string; // "Notes"
  reconcileNotesPlaceholder: string; // placeholder du champ notes
  reconcileCalculating: string; // "Calculating..."
  reconcileCalculate: string; // "Calculate Reconciliation"

  // ── ReconciliationWorkflow : panneau de résultats ────────────
  reconcileResult: string; // "Reconciliation Result"
  reconcileBankReconciled: string; // "Bank (Reconciled)"
  reconcileBankLabel: string; // "Bank:"
  reconcileChequesLabel: string; // " − Cheques: "
  reconcileTransitLabel: string; // " + Transit: "
  reconcileSafeRegister: string; // "SAFE Register"
  reconcileSafeRegisterDesc: string; // "Sum of all recorded transactions"
  reconcileDiscrepancy: string; // "Discrepancy"
  reconcileBalancedReady: string; // "Balanced — ready to certify"
  reconcileMustBeZero: string; // "Must be $0.00 to certify"
  reconcileFoundationInterestInline: string; // "LFO Interest:" / "Intérêts au fonds du Barreau :"
  reconcilePaidSuffix: string; // " (paid)" / " (versés)"
  reconcilePendingSuffix: string; // " (pending)" / " (à verser)"
  reconcileCertifiedBy: (name: string, date: string) => string; // "Certified by X on Y"

  // ── ReconciliationWorkflow : historique ──────────────────────
  reconcileHistoryTitle: string; // "Reconciliation History"
  reconcileColPeriod: string; // "Period"
  reconcileColBank: string; // "Bank"
  reconcileColRegister: string; // "Register"
  reconcileColDiscrepancy: string; // "Discrepancy"
  reconcileColStatus: string; // "Status"
  reconcileColCertifiedBy: string; // "Certified By"

  // ── LSOReportGenerator : formulaire ──────────────────────────
  reportFieldPeriod: string; // "Period (YYYY-MM)"
  reportFieldType: string; // "Type"
  reportTypeMonthly: string; // "Monthly"
  reportTypeQuarterly: string; // "Quarterly"
  reportTypeAnnual: string; // "Annual"
  reportLoading: string; // "Loading..."
  reportPreview: string; // "Preview"

  // ── LSOReportGenerator : aperçu ──────────────────────────────
  reportSaving: string; // "Saving..."
  reportSave: string; // "Save Report"
  reportMetaLine: (periode: string, type: string, generatedBy: string) => string; // "Period: ... | Type: ... | Generated by ..."
  reportOpeningBalance: string; // "Opening Balance"
  reportTotalDeposits: string; // "Total Deposits"
  reportTotalWithdrawals: string; // "Total Withdrawals"
  reportClosingBalance: string; // "Closing Balance"
  reportBankBalance: string; // "Bank Balance"
  reportRegisterBalance: string; // "Register Balance"
  reportDiscrepancy: string; // "Discrepancy"
  reportCertifiedBy: (name: string) => string; // "Certified by X"
  reportCertifiedOn: (date: string) => string; // " on Y"
  reportTransactionJournal: (count: number) => string; // "Transaction Journal (N entries)"
  reportColDate: string; // "Date"
  reportColType: string; // "Type"
  reportColClientMatter: string; // "Client / Matter"
  reportColDescription: string; // "Description"
  reportColAmount: string; // "Amount"
  reportColBalance: string; // "Balance"

  // ── LSOReportGenerator : rapports sauvegardés ────────────────
  reportSavedTitle: string; // "Saved Reports"
  reportColPeriod: string; // "Period"
  reportColStatus: string; // "Status"
  reportColGenerated: string; // "Generated"
  reportColBy: string; // "By"
  reportColReconciliation: string; // "Reconciliation"
  reportReconciliationNone: string; // "None"
  reportColAction: string; // "Action"

  // ── Dashboard fidéicommis ────────────────────────────────────
  reconciliationButton: string;
  complianceReportsButton: string;

  // ── Carte d'alerte de rapprochement ──────────────────────────
  alertUpToDate: string;
  alertOverdueCritical: (daysSinceMonthEnd: number) => string;
  alertOverdueCriticalDetail: (periode: string) => string;
  alertDue: (daysRemaining: number) => string;
  alertDueDetail: (periode: string) => string;
  alertPending: (periode: string) => string;
  alertPendingDetail: (daysRemaining: number) => string;
};

const QC: TrustRegulatorCopy = {
  isQuebec: true,
  authority: "Barreau du Québec",
  regulationShort: "Règlement B-1, r. 5",
  regulationLong:
    "Règlement sur la comptabilité et les normes d'exercice professionnel des avocats (B-1, r. 5)",

  trustReconciliationTitle: "Rapprochement du fidéicommis",
  trustReconciliationDesc:
    "Rapprochement mensuel à trois voies (Barreau du Québec, B-1, r. 5). Comparez le relevé bancaire, le registre SAFE et les soldes par dossier.",
  trustReportsTitle: "Rapports de conformité — fidéicommis",
  trustReportsDesc:
    "Générez des rapports de conformité (Barreau du Québec, B-1, r. 5) prêts pour une inspection. Inclut le journal des opérations, le rapprochement à trois voies et le sommaire des intérêts.",
  backToTrustAccounts: "Retour aux comptes en fidéicommis",
  complianceTitle: "Tableau de conformité",
  complianceDesc:
    "État de conformité en temps réel : compte en fidéicommis (Barreau du Québec, B-1, r. 5), obligations professionnelles et protection des renseignements (Loi 25).",

  reconciliationHeading: "Rapprochement du fidéicommis à trois voies",
  certificationStatement:
    "Je certifie que ce rapprochement à trois voies est exact, conformément au Règlement B-1, r. 5 du Barreau du Québec.",
  reportGeneratorTitle: "Générateur de rapport de conformité",
  reportGeneratorDesc:
    "Générez un rapport de conformité du compte en fidéicommis, prêt pour une inspection du Barreau du Québec (B-1, r. 5).",
  reportStatementTitle: "Relevé du compte en fidéicommis",
  threeWayReconciliation: "Rapprochement à trois voies",
  foundationInterestLabel: "Intérêts versés au fonds du Barreau :",

  reconcileNewPeriod: "Nouvelle période",
  reconcileFormIntro:
    "Saisissez le solde de votre relevé bancaire et les éléments en suspens. SAFE calcule automatiquement le solde du registre à partir des opérations enregistrées.",
  reconcileFieldPeriod: "Période (AAAA-MM)",
  reconcileFieldBankStatementBalance: "Solde du relevé bancaire ($)",
  reconcileFieldOutstandingCheques: "Chèques en circulation ($)",
  reconcileFieldDepositsInTransit: "Dépôts en transit ($)",
  reconcileFieldFoundationInterestPayable: "Intérêts au fonds du Barreau à verser ($)",
  reconcileFieldNotes: "Notes",
  reconcileNotesPlaceholder: "Notes facultatives pour ce rapprochement…",
  reconcileCalculating: "Calcul en cours…",
  reconcileCalculate: "Calculer le rapprochement",

  reconcileResult: "Résultat du rapprochement",
  reconcileBankReconciled: "Banque (rapprochée)",
  reconcileBankLabel: "Banque :",
  reconcileChequesLabel: " − Chèques : ",
  reconcileTransitLabel: " + Transit : ",
  reconcileSafeRegister: "Registre SAFE",
  reconcileSafeRegisterDesc: "Somme de toutes les opérations enregistrées",
  reconcileDiscrepancy: "Écart",
  reconcileBalancedReady: "Équilibré — prêt à certifier",
  reconcileMustBeZero: "Doit être de 0,00 $ pour certifier",
  reconcileFoundationInterestInline: "Intérêts au fonds du Barreau :",
  reconcilePaidSuffix: " (versés)",
  reconcilePendingSuffix: " (à verser)",
  reconcileCertifiedBy: (name, date) => `Certifié par ${name} le ${date}`,

  reconcileHistoryTitle: "Historique des rapprochements",
  reconcileColPeriod: "Période",
  reconcileColBank: "Banque",
  reconcileColRegister: "Registre",
  reconcileColDiscrepancy: "Écart",
  reconcileColStatus: "Statut",
  reconcileColCertifiedBy: "Certifié par",

  reportFieldPeriod: "Période (AAAA-MM)",
  reportFieldType: "Type",
  reportTypeMonthly: "Mensuel",
  reportTypeQuarterly: "Trimestriel",
  reportTypeAnnual: "Annuel",
  reportLoading: "Chargement…",
  reportPreview: "Aperçu",

  reportSaving: "Enregistrement…",
  reportSave: "Enregistrer le rapport",
  reportMetaLine: (periode, type, generatedBy) =>
    `Période : ${periode} | Type : ${type} | Généré par ${generatedBy}`,
  reportOpeningBalance: "Solde d'ouverture",
  reportTotalDeposits: "Total des dépôts",
  reportTotalWithdrawals: "Total des retraits",
  reportClosingBalance: "Solde de clôture",
  reportBankBalance: "Solde bancaire",
  reportRegisterBalance: "Solde du registre",
  reportDiscrepancy: "Écart",
  reportCertifiedBy: (name) => `Certifié par ${name}`,
  reportCertifiedOn: (date) => ` le ${date}`,
  reportTransactionJournal: (count) =>
    `Journal des opérations (${count} entrée${count > 1 ? "s" : ""})`,
  reportColDate: "Date",
  reportColType: "Type",
  reportColClientMatter: "Client / Dossier",
  reportColDescription: "Description",
  reportColAmount: "Montant",
  reportColBalance: "Solde",

  reportSavedTitle: "Rapports enregistrés",
  reportColPeriod: "Période",
  reportColStatus: "Statut",
  reportColGenerated: "Généré le",
  reportColBy: "Par",
  reportColReconciliation: "Rapprochement",
  reportReconciliationNone: "Aucun",
  reportColAction: "Action",

  reconciliationButton: "Rapprochement",
  complianceReportsButton: "Rapports de conformité",

  alertUpToDate: "Rapprochement du fidéicommis à jour",
  alertOverdueCritical: (d) =>
    `Rapprochement du fidéicommis en retard — ${d} jour${d > 1 ? "s" : ""} depuis la fin du mois`,
  alertOverdueCriticalDetail: (p) =>
    `Le Barreau du Québec (B-1, r. 5) exige un rapprochement mensuel à trois voies. Période ${p} non certifiée.`,
  alertDue: () => "Rapprochement du fidéicommis à effectuer",
  alertDueDetail: (p) => `La période ${p} doit être rapprochée et certifiée.`,
  alertPending: (p) => `Rapprochement du fidéicommis à faire pour ${p}`,
  alertPendingDetail: () => "Rapprochement mensuel à trois voies à certifier.",
};

const ON: TrustRegulatorCopy = {
  isQuebec: false,
  authority: "Law Society of Ontario (LSO)",
  regulationShort: "By-Law 9",
  regulationLong: "By-Law 9, sec. 9.01 (LSO)",

  trustReconciliationTitle: "Trust Reconciliation",
  trustReconciliationDesc:
    "Monthly 3-way reconciliation per By-Law 9, LSO. Compare bank statement, SAFE register, and per-matter balances.",
  trustReportsTitle: "Trust Compliance Reports",
  trustReportsDesc:
    "Generate LSO By-Law 9 compliance reports for spot audit readiness. Includes transaction journal, 3-way reconciliation, and LFO interest summary.",
  backToTrustAccounts: "Back to Trust Accounts",
  complianceTitle: "Compliance Dashboard",
  complianceDesc:
    "Real-time compliance status for By-Law 9 (LSO), FINTRAC, PIPEDA, and professional obligations.",

  reconciliationHeading: "3-Way Trust Reconciliation",
  certificationStatement:
    "I certify that this 3-way reconciliation is accurate per By-Law 9, LSO.",
  reportGeneratorTitle: "LSO Compliance Report Generator",
  reportGeneratorDesc:
    "Generate a trust account compliance report formatted for By-Law 9, LSO spot audit.",
  reportStatementTitle: "Trust Account Statement",
  threeWayReconciliation: "3-Way Reconciliation",
  foundationInterestLabel: "Law Foundation of Ontario interest:",

  reconcileNewPeriod: "New Period",
  reconcileFormIntro:
    "Enter your bank statement balance and outstanding items. SAFE calculates the register balance automatically from recorded transactions.",
  reconcileFieldPeriod: "Period (YYYY-MM)",
  reconcileFieldBankStatementBalance: "Bank Statement Balance ($)",
  reconcileFieldOutstandingCheques: "Outstanding Cheques ($)",
  reconcileFieldDepositsInTransit: "Deposits in Transit ($)",
  reconcileFieldFoundationInterestPayable: "LFO Interest Payable ($)",
  reconcileFieldNotes: "Notes",
  reconcileNotesPlaceholder: "Optional notes for this reconciliation...",
  reconcileCalculating: "Calculating...",
  reconcileCalculate: "Calculate Reconciliation",

  reconcileResult: "Reconciliation Result",
  reconcileBankReconciled: "Bank (Reconciled)",
  reconcileBankLabel: "Bank:",
  reconcileChequesLabel: " − Cheques: ",
  reconcileTransitLabel: " + Transit: ",
  reconcileSafeRegister: "SAFE Register",
  reconcileSafeRegisterDesc: "Sum of all recorded transactions",
  reconcileDiscrepancy: "Discrepancy",
  reconcileBalancedReady: "Balanced — ready to certify",
  reconcileMustBeZero: "Must be $0.00 to certify",
  reconcileFoundationInterestInline: "LFO Interest:",
  reconcilePaidSuffix: " (paid)",
  reconcilePendingSuffix: " (pending)",
  reconcileCertifiedBy: (name, date) => `Certified by ${name} on ${date}`,

  reconcileHistoryTitle: "Reconciliation History",
  reconcileColPeriod: "Period",
  reconcileColBank: "Bank",
  reconcileColRegister: "Register",
  reconcileColDiscrepancy: "Discrepancy",
  reconcileColStatus: "Status",
  reconcileColCertifiedBy: "Certified By",

  reportFieldPeriod: "Period (YYYY-MM)",
  reportFieldType: "Type",
  reportTypeMonthly: "Monthly",
  reportTypeQuarterly: "Quarterly",
  reportTypeAnnual: "Annual",
  reportLoading: "Loading...",
  reportPreview: "Preview",

  reportSaving: "Saving...",
  reportSave: "Save Report",
  reportMetaLine: (periode, type, generatedBy) =>
    `Period: ${periode} | Type: ${type} | Generated by ${generatedBy}`,
  reportOpeningBalance: "Opening Balance",
  reportTotalDeposits: "Total Deposits",
  reportTotalWithdrawals: "Total Withdrawals",
  reportClosingBalance: "Closing Balance",
  reportBankBalance: "Bank Balance",
  reportRegisterBalance: "Register Balance",
  reportDiscrepancy: "Discrepancy",
  reportCertifiedBy: (name) => `Certified by ${name}`,
  reportCertifiedOn: (date) => ` on ${date}`,
  reportTransactionJournal: (count) => `Transaction Journal (${count} entries)`,
  reportColDate: "Date",
  reportColType: "Type",
  reportColClientMatter: "Client / Matter",
  reportColDescription: "Description",
  reportColAmount: "Amount",
  reportColBalance: "Balance",

  reportSavedTitle: "Saved Reports",
  reportColPeriod: "Period",
  reportColStatus: "Status",
  reportColGenerated: "Generated",
  reportColBy: "By",
  reportColReconciliation: "Reconciliation",
  reportReconciliationNone: "None",
  reportColAction: "Action",

  reconciliationButton: "Reconciliation",
  complianceReportsButton: "Compliance Reports",

  alertUpToDate: "Trust reconciliation up to date",
  alertOverdueCritical: (d) =>
    `Trust reconciliation overdue — ${d} days since month-end`,
  alertOverdueCriticalDetail: (p) =>
    `By-Law 9 requires reconciliation within 25 days. Period ${p} not certified.`,
  alertDue: (r) => `Trust reconciliation due — ${r} days remaining`,
  alertDueDetail: (p) => `Period ${p} needs to be reconciled and certified.`,
  alertPending: (p) => `Trust reconciliation pending for ${p}`,
  alertPendingDetail: (r) => `${r} days until By-Law 9 deadline.`,
};

/**
 * Renvoie la terminologie du fidéicommis selon la province du cabinet.
 * QC → Barreau du Québec (B-1, r. 5), français. Toute autre valeur (ou absente)
 * → LSO Ontario, anglais (comportement historique inchangé).
 */
export function getTrustRegulatorCopy(province?: string | null): TrustRegulatorCopy {
  return (province ?? "").toUpperCase() === "QC" ? QC : ON;
}
