/**
 * Chemins de navigation centralisés.
 * Une seule source de vérité pour les routes de l'app (plan: renforcement logique métier).
 */

export const routes = {
  tableauDeBord: "/tableau-de-bord",
  aujourdhui: "/aujourdhui",
  clients: "/clients",
  client: (id: string) => `/clients/${id}`,
  clientNouveau: "/clients/nouveau",
  clientVerificationIdentite: (id: string) => `/clients/${id}/verification-identite`,
  dossiers: "/dossiers",
  dossier: (id: string) => `/dossiers/${id}`,
  dossierNouveau: (clientId?: string) =>
    clientId ? `/dossiers/nouveau?clientId=${encodeURIComponent(clientId)}` : "/dossiers/nouveau",
  temps: "/temps",
  mesHeures: "/mes-heures",
  facturation: "/facturation",
  /** Section "Facturables" intégrée à /facturation. La route /facturation/honoraires redirige ici. */
  facturationHonoraires: "/facturation#facturables",
  facturationHonorairesClient: (clientId: string) => `/facturation/honoraires/${clientId}`,
  facturationFactureNouvelle: "/facturation/nouvelle",
  facturationFactureApercu: (id: string) => `/facturation/factures/${id}`,
  /** @deprecated Le chemin affiche maintenant l'aperçu canonique de la facture. */
  facturationFactureEdit: (id: string) => `/facturation/factures/${id}`,
  /** Lien public pour que le client consulte sa facture (sans auth) */
  factureClient: (token: string) => `/facture/${token}`,
  facturationVerification: "/facturation/verification",
  facturationSuivi: "/facturation/suivi",
  facturationPaiements: "/facturation/paiements",
  facturationNotesCredit: "/facturation/notes-de-credit",
  facturationFrais: "/facturation/frais",
  journalDepenses: "/journal/depenses",
  rapports: "/rapports",
  journalGeneral: "/journal/general",
  comptabilite: "/comptabilite",
  comptabiliteTab: (tab: "general" | "depenses" | "paiements") => `/comptabilite?tab=${tab}`,
  parametres: "/parametres",
  parametresCabinet: "/parametres/cabinet",
  parametresAbonnement: "/parametres/abonnement",
  parametresAudit: "/parametres/audit",
  parametresRetention: "/parametres/retention",
  parametresEnvoiFacture: "/parametres/envoi-facture",
  parametresFacture: "/parametres/facture",
  /** @deprecated /parametres/equipe a été supprimée. Utiliser routes.employees. */
  parametresEquipe: "/employees",
  rejoindre: (token: string) => `/rejoindre/${token}`,
  employees: "/employees",
  employee: (id: string) => `/employees/${id}`,
  employeeNouveau: "/employees/nouveau",
  comptes: "/comptes",
  connexion: "/connexion",
  inscription: "/inscription",
  onboarding: "/onboarding",
  auditOnboarding: "/audit-gratuit",
  outils: "/outils",
  gestion: "/gestion",
  gestionLexTrack: "/gestion/lextrack",
  gestionLexTrackDossier: (dossierId: string) => `/gestion/lextrack?dossierId=${encodeURIComponent(dossierId)}`,
  gestionAssistante: "/gestion/assistante",
  safeImport: "/import",
  edition: "/edition",
  editionBibliotheque: "/edition/bibliotheque",
  editionDossier: (dossierId: string) => `/edition/${dossierId}`,
  editionDocument: (dossierId: string, docId: string) => `/edition/${dossierId}/${docId}`,
} as const;
