import type { DossierType } from "@prisma/client";

export interface SectionTemplate {
  sectionKey: string;
  label: string;
  ordre: number;
  sourceReglementaire?: string;
  icone?: string;
  description?: string;
  privilegiee?: boolean;
}

const DROIT_FAMILLE: SectionTemplate[] = [
  {
    sectionKey: "mandat",
    label: "Mandat et engagement",
    ordre: 0,
    sourceReglementaire: "RCNEPA art. 15-16 · Code déonto. art. 3.08",
    icone: "FileSignature",
    description: "Ouverture du mandat, vérification identité, conflits d'intérêts",
  },
  {
    sectionKey: "pieces-madame",
    label: "Pièces Madame (P-)",
    ordre: 1,
    sourceReglementaire: "Règl. Cour Qc art. 13",
    icone: "FolderOpen",
    description: "Pièces P-1 à P-35 — partie demanderesse",
  },
  {
    sectionKey: "pieces-monsieur",
    label: "Pièces Monsieur (D-)",
    ordre: 2,
    sourceReglementaire: "Règl. Cour Qc art. 13",
    icone: "FolderClosed",
    description: "Pièces D-1 à D-35 — partie défenderesse",
  },
  {
    sectionKey: "procedures",
    label: "Procédures",
    ordre: 3,
    sourceReglementaire: "C.p.c. art. 109 et s.",
    icone: "Scale",
    description: "Actes introductifs, demandes, réponses, protocoles",
  },
  {
    sectionKey: "jugements",
    label: "Jugements et ordonnances",
    ordre: 4,
    sourceReglementaire: "C.p.c. art. 322 et s.",
    icone: "Gavel",
    description: "Ordonnances provisoires, jugement final, homologations",
  },
  {
    sectionKey: "correspondance",
    label: "Correspondance",
    ordre: 5,
    icone: "Mail",
    description: "Échanges avec la partie adverse, le tribunal et les tiers",
  },
  {
    sectionKey: "fideicommis",
    label: "Fidéicommis",
    ordre: 6,
    sourceReglementaire: "RCNEPA art. 14-19, 44-55",
    icone: "Wallet",
    description: "Provisions, remboursements, relevé de compte en fidéicommis",
    privilegiee: true,
  },
  {
    sectionKey: "notes-honoraires",
    label: "Notes et honoraires",
    ordre: 7,
    icone: "StickyNote",
    description: "Notes internes, états de compte, factures",
    privilegiee: true,
  },
  {
    sectionKey: "fermeture",
    label: "Fermeture du dossier",
    ordre: 8,
    sourceReglementaire: "RCNEPA art. 18-19",
    icone: "Archive",
    description: "Checklist de fermeture, archivage, délai de conservation",
  },
];

const LITIGE_CIVIL: SectionTemplate[] = [
  {
    sectionKey: "mandat",
    label: "Mandat et engagement",
    ordre: 0,
    sourceReglementaire: "RCNEPA art. 15-16 · Code déonto. art. 3.08",
    icone: "FileSignature",
    description: "Ouverture, vérification identité et conflits, contrat de mandat",
  },
  {
    sectionKey: "phase-prejudiciaire",
    label: "Phase préjudiciaire",
    ordre: 1,
    sourceReglementaire: "C.p.c. art. 1, 2, 7, 19, 21",
    icone: "MessageSquareWarning",
    description: "Mise en demeure, protocole de l'instance, tentative de règlement",
  },
  {
    sectionKey: "pieces-demanderesse",
    label: "Pièces demanderesse (P-)",
    ordre: 2,
    sourceReglementaire: "Règl. Cour Qc art. 13",
    icone: "FolderOpen",
    description: "Pièces P-1 et suivantes — partie demanderesse",
  },
  {
    sectionKey: "pieces-defendeur",
    label: "Pièces défendeur (D-)",
    ordre: 3,
    sourceReglementaire: "Règl. Cour Qc art. 13",
    icone: "FolderClosed",
    description: "Pièces D-1 et suivantes — partie défenderesse",
  },
  {
    sectionKey: "procedures",
    label: "Procédures",
    ordre: 4,
    sourceReglementaire: "C.p.c. art. 109 et s.",
    icone: "Scale",
    description: "Demande introductive, défense, demandes incidentes",
  },
  {
    sectionKey: "interrogatoires",
    label: "Interrogatoires et expertises",
    ordre: 5,
    sourceReglementaire: "C.p.c. art. 221-231, 232-247",
    icone: "ClipboardList",
    description: "Interrogatoires préalables, rapports d'expertise, engagements",
  },
  {
    sectionKey: "jugements",
    label: "Jugements",
    ordre: 6,
    sourceReglementaire: "C.p.c. art. 322 et s.",
    icone: "Gavel",
    description: "Jugement de première instance, appel, exécution",
  },
  {
    sectionKey: "correspondance",
    label: "Correspondance",
    ordre: 7,
    icone: "Mail",
    description: "Échanges avec partie adverse, tribunal, huissier, expert",
  },
  {
    sectionKey: "fideicommis",
    label: "Fidéicommis",
    ordre: 8,
    sourceReglementaire: "RCNEPA art. 14-19, 44-55",
    icone: "Wallet",
    description: "Provisions, consignations, débours (huissier, sténographe, expert)",
    privilegiee: true,
  },
  {
    sectionKey: "notes-honoraires",
    label: "Notes et honoraires",
    ordre: 9,
    icone: "StickyNote",
    privilegiee: true,
  },
  {
    sectionKey: "fermeture",
    label: "Fermeture du dossier",
    ordre: 10,
    sourceReglementaire: "RCNEPA art. 18-19 · C.p.c. art. 173",
    icone: "Archive",
    description: "Compteur 6 mois (art. 173 C.p.c.), archivage, conservation",
  },
];

const CRIMINEL: SectionTemplate[] = [
  {
    sectionKey: "mandat",
    label: "Mandat et engagement",
    ordre: 0,
    sourceReglementaire: "RCNEPA · Code déonto. art. 3.08 · LAJ",
    icone: "FileSignature",
    description: "Mandat, aide juridique (LAJ) ou privé, vérification identité",
  },
  {
    sectionKey: "divulgation",
    label: "Divulgation DPCP",
    ordre: 1,
    sourceReglementaire: "R. c. Stinchcombe [1991] 3 RCS 326",
    icone: "BookOpen",
    description: "Registre de divulgation, demandes supplémentaires, accusé réception",
  },
  {
    sectionKey: "formulaires",
    label: "Formulaires prescrits (C.cr.)",
    ordre: 2,
    sourceReglementaire: "Code criminel annexes — formulaires 2, 5, 7, 10, 11, 11.1, 12, 28, 32, 33",
    icone: "FileText",
    description: "Formulaires de comparution, libération, engagements, interdictions",
  },
  {
    sectionKey: "procedures",
    label: "Actes de procédure",
    ordre: 3,
    sourceReglementaire: "Code criminel · Règles Cour sup. ch. crim. 2025",
    icone: "Scale",
    description: "Mise en accusation, dénonciation, demandes préliminaires (Garofoli, Jordan)",
  },
  {
    sectionKey: "comparutions",
    label: "Comparutions et dates",
    ordre: 4,
    sourceReglementaire: "R. c. Jordan 2016 CSC 27 — plafond 18 mois (Cour Qc) / 30 mois (Cour sup.)",
    icone: "Calendar",
    description: "Calendrier des comparutions, suivi délai Jordan, libération sous conditions",
  },
  {
    sectionKey: "correspondance",
    label: "Correspondance",
    ordre: 5,
    icone: "Mail",
    description: "Échanges avec DPCP, tribunal, services correctionnels",
  },
  {
    sectionKey: "fideicommis",
    label: "Fidéicommis",
    ordre: 6,
    sourceReglementaire: "RCNEPA art. 14-19, 44-55",
    icone: "Wallet",
    privilegiee: true,
  },
  {
    sectionKey: "notes-honoraires",
    label: "Notes et honoraires",
    ordre: 7,
    icone: "StickyNote",
    privilegiee: true,
  },
  {
    sectionKey: "fermeture",
    label: "Fermeture du dossier",
    ordre: 8,
    sourceReglementaire: "RCNEPA art. 18-19",
    icone: "Archive",
  },
];

const IMMIGRATION: SectionTemplate[] = [
  {
    sectionKey: "mandat",
    label: "Mandat et engagement",
    ordre: 0,
    sourceReglementaire: "RCNEPA · Code déonto. art. 3.08 · IMM 5476",
    icone: "FileSignature",
    description: "Mandat, formulaire IMM 5476 (représentant autorisé), vérification identité",
  },
  {
    sectionKey: "immigration",
    label: "Suivi IRCC / MIFI",
    ordre: 1,
    sourceReglementaire: "LIPR art. 91 · RIPR art. 183(5) · Accord Canada-Québec 1991",
    icone: "Globe",
    description: "Statut de la demande, numéro IRCC, délais biométrie, EMI, statut implicite",
  },
  {
    sectionKey: "formulaires",
    label: "Formulaires IMM / MIFI",
    ordre: 2,
    sourceReglementaire: "IRCC · MIFI — formulaires IMM 5257, 1294, 1295, 0008, CSQ, CAQ",
    icone: "FileText",
    description: "Formulaires de demande, annexes, paiements IRCC et MIFI",
  },
  {
    sectionKey: "pieces",
    label: "Pièces et documents",
    ordre: 3,
    sourceReglementaire: "LIPR · Instructions ministérielles IRCC",
    icone: "FolderOpen",
    description: "Passeport, photos, certificats de police (GRC + pays), EMI, traductions assermentées",
  },
  {
    sectionKey: "correspondance",
    label: "Correspondance",
    ordre: 4,
    icone: "Mail",
    description: "Échanges avec IRCC, MIFI, ambassades, demandes de renseignements ATIP",
  },
  {
    sectionKey: "notes-honoraires",
    label: "Notes et honoraires",
    ordre: 5,
    icone: "StickyNote",
    privilegiee: true,
  },
  {
    sectionKey: "fermeture",
    label: "Fermeture du dossier",
    ordre: 6,
    sourceReglementaire: "RCNEPA art. 18-19",
    icone: "Archive",
  },
];

const IMMOBILIER: SectionTemplate[] = [
  {
    sectionKey: "mandat",
    label: "Mandat et engagement",
    ordre: 0,
    sourceReglementaire: "RCNEPA · LRPCFAT · Code déonto. art. 3.08",
    icone: "FileSignature",
    description: "Mandat, vérification FINTRAC, identification client (art. 3 LRPCFAT)",
  },
  {
    sectionKey: "formulaires",
    label: "Actes et formulaires",
    ordre: 1,
    sourceReglementaire: "Code civil art. 1553 et s. · RDPRM · Loi sur le notariat",
    icone: "FileText",
    description: "Promesse d'achat, acte de vente, hypothèque, quittance, RDPRM",
  },
  {
    sectionKey: "procedures",
    label: "Procédures et titres",
    ordre: 2,
    sourceReglementaire: "Code civil art. 2938 et s.",
    icone: "Scale",
    description: "Examen de titres, rapport de recherche, publication des droits",
  },
  {
    sectionKey: "correspondance",
    label: "Correspondance",
    ordre: 3,
    icone: "Mail",
    description: "Échanges avec courtiers, prêteurs, parties, notaire",
  },
  {
    sectionKey: "fideicommis",
    label: "Fidéicommis",
    ordre: 4,
    sourceReglementaire: "RCNEPA art. 14-19, 44-55",
    icone: "Wallet",
    description: "Dépôt, débours, ajustements, solde à la clôture",
    privilegiee: true,
  },
  {
    sectionKey: "notes-honoraires",
    label: "Notes et honoraires",
    ordre: 5,
    icone: "StickyNote",
    privilegiee: true,
  },
  {
    sectionKey: "fermeture",
    label: "Fermeture du dossier",
    ordre: 6,
    sourceReglementaire: "RCNEPA art. 18-19",
    icone: "Archive",
    description: "Closing, remise des actes, archivage",
  },
];

const CORPORATE: SectionTemplate[] = [
  {
    sectionKey: "mandat",
    label: "Mandat et engagement",
    ordre: 0,
    sourceReglementaire: "RCNEPA · LRPCFAT · Code déonto. art. 3.08",
    icone: "FileSignature",
    description: "Mandat, identification client (bénéficiaires ultimes LSAQ art. 35.1)",
  },
  {
    sectionKey: "registres",
    label: "Livre des minutes et registres",
    ordre: 1,
    sourceReglementaire: "LSAQ art. 35.1, 89 et s. · LCSA art. 20 et s. · LPLE · REQ",
    icone: "BookOpen",
    description: "Registres des actionnaires, administrateurs, bénéficiaires ultimes, transferts",
  },
  {
    sectionKey: "formulaires",
    label: "Formulaires REQ / Corporations Canada",
    ordre: 2,
    sourceReglementaire: "LSAQ · LCSA · Loi sur la publicité légale (LPLE)",
    icone: "FileText",
    description: "Déclarations initiales, modifications, résolutions, statuts de constitution",
  },
  {
    sectionKey: "diligence",
    label: "Vérification diligente",
    ordre: 3,
    sourceReglementaire: "Code civil art. 1375 et s. · LIPR (si multiculturel)",
    icone: "Search",
    description: "Data room, checklist due diligence, contrats matériels, litiges pendants",
  },
  {
    sectionKey: "correspondance",
    label: "Correspondance",
    ordre: 4,
    icone: "Mail",
    description: "Échanges avec actionnaires, avocats des parties, ARC, REQ",
  },
  {
    sectionKey: "fideicommis",
    label: "Fidéicommis transactionnel",
    ordre: 5,
    sourceReglementaire: "RCNEPA art. 14-19, 44-55",
    icone: "Wallet",
    description: "Escrow, ajustements, conditions de closing, solde final",
    privilegiee: true,
  },
  {
    sectionKey: "notes-honoraires",
    label: "Notes et honoraires",
    ordre: 6,
    icone: "StickyNote",
    privilegiee: true,
  },
  {
    sectionKey: "fermeture",
    label: "Fermeture du dossier",
    ordre: 7,
    sourceReglementaire: "RCNEPA art. 18-19",
    icone: "Archive",
    description: "Closing package, obligations récurrentes post-closing, archivage",
  },
];

const DROIT_TRAVAIL: SectionTemplate[] = [
  {
    sectionKey: "mandat",
    label: "Mandat et engagement",
    ordre: 0,
    sourceReglementaire: "RCNEPA · Code déonto. art. 3.08",
    icone: "FileSignature",
    description: "Mandat, qualification du forum (CNESST / TAT / arbitrage / CDPDJ / CCRI)",
  },
  {
    sectionKey: "recours",
    label: "Qualification et recours",
    ordre: 1,
    sourceReglementaire: "LNT art. 123, 123.7, 124 · Code du travail · LSST · LATMP",
    icone: "Scale",
    description: "Délais de prescription (45j art. 124, 45j art. 123, 2 ans art. 123.7), choix du forum",
  },
  {
    sectionKey: "formulaires",
    label: "Formulaires et plaintes",
    ordre: 2,
    sourceReglementaire: "LNT · Code du travail · LATMP · Charte · Loi 42",
    icone: "FileText",
    description: "Plaintes CNESST, formules TAT, plaintes harcèlement (Loi 42)",
  },
  {
    sectionKey: "pieces",
    label: "Pièces et preuve",
    ordre: 3,
    sourceReglementaire: "Règles TAT · Règles de preuve",
    icone: "FolderOpen",
    description: "Contrat de travail, politiques, avis de cessation, registres de temps, témoignages",
  },
  {
    sectionKey: "procedures",
    label: "Procédures et audiences",
    ordre: 4,
    sourceReglementaire: "LITAT · Règles TAT · Code du travail",
    icone: "Gavel",
    description: "Médiation, conférence préparatoire, audience, décision arbitrale",
  },
  {
    sectionKey: "correspondance",
    label: "Correspondance",
    ordre: 5,
    icone: "Mail",
    description: "Échanges avec employeur, syndicat, CNESST, TAT",
  },
  {
    sectionKey: "fideicommis",
    label: "Fidéicommis",
    ordre: 6,
    sourceReglementaire: "RCNEPA art. 14-19, 44-55",
    icone: "Wallet",
    privilegiee: true,
  },
  {
    sectionKey: "notes-honoraires",
    label: "Notes et honoraires",
    ordre: 7,
    icone: "StickyNote",
    description: "Honoraires conditionnels, états de compte, entente de règlement",
    privilegiee: true,
  },
  {
    sectionKey: "fermeture",
    label: "Fermeture du dossier",
    ordre: 8,
    sourceReglementaire: "RCNEPA art. 18-19",
    icone: "Archive",
  },
];

const AUTRE: SectionTemplate[] = [
  {
    sectionKey: "mandat",
    label: "Mandat et engagement",
    ordre: 0,
    sourceReglementaire: "RCNEPA · Code déonto. art. 3.08",
    icone: "FileSignature",
  },
  {
    sectionKey: "formulaires",
    label: "Formulaires et documents",
    ordre: 1,
    icone: "FileText",
  },
  {
    sectionKey: "procedures",
    label: "Procédures",
    ordre: 2,
    icone: "Scale",
  },
  {
    sectionKey: "correspondance",
    label: "Correspondance",
    ordre: 3,
    icone: "Mail",
  },
  {
    sectionKey: "notes-honoraires",
    label: "Notes et honoraires",
    ordre: 4,
    icone: "StickyNote",
    privilegiee: true,
  },
  {
    sectionKey: "fermeture",
    label: "Fermeture du dossier",
    ordre: 5,
    sourceReglementaire: "RCNEPA art. 18-19",
    icone: "Archive",
  },
];

export const CARTABLE_TEMPLATES: Record<DossierType, SectionTemplate[]> = {
  droit_famille: DROIT_FAMILLE,
  litige_civil: LITIGE_CIVIL,
  criminel: CRIMINEL,
  immigration: IMMIGRATION,
  immobilier: IMMOBILIER,
  corporate: CORPORATE,
  autre: AUTRE,
};

export function getCartableTemplate(type: DossierType | null | undefined): SectionTemplate[] {
  if (!type) return AUTRE;
  return CARTABLE_TEMPLATES[type] ?? AUTRE;
}
